name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        options:
          - 'staging'
          - 'production'
        type: choice

jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Print variable
        run: |
          echo ${{ vars.TEST_YAML_ARRAY }}
      - name: Set matrix for second job
        id: set-matrix
        run: echo 'locations=${{ vars.TEST_YAML_ARRAY }}' >> $GITHUB_OUTPUT

  second-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        location: ${{ needs.first-job.outputs.locations }}
    steps:
      - name: Print variable
        run: |
          echo "Location: ${{ matrix.location }}"
